# Generated by Django 6.0.6 on 2026-08-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_viagem_valor_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='valor_adiantamento',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Adiantamento'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='valor_quitacao',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Quitação'),
        ),
    ]
