# Generated by Django 6.0.6 on 2026-08-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_caixa_valor_gasto_caixa_valor_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='mic',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='nota_fiscal',
        ),
    ]
