# Generated by Django 6.0.6 on 2026-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_abastecida_options_viagem_contratante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(max_length=17, verbose_name='Chassi'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(db_index=True, max_length=7, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=11, verbose_name='RENAVAM'),
        ),
    ]
