# Generated by Django 6.0.5 on 2026-05-28 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_gasto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Gasto')),
                ('centro_de_custo', models.CharField(max_length=100, verbose_name='Centro de Custo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxos de Caixa',
                'db_table': 'caixa',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CNH')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='RENAVAM')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(verbose_name='Ano do Modelo')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_viagem', 'Em Viagem'), ('manutencao', 'Em Manutenção'), ('vendido', 'Vendido')], default='disponivel', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculos',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('data_adiantamento', models.DateField(blank=True, null=True, verbose_name='Data do Adiantamento')),
                ('data_quitacao', models.DateField(blank=True, null=True, verbose_name='Data da Quitação')),
                ('local_inicio', models.CharField(max_length=255, verbose_name='Local de Início')),
                ('local_final', models.CharField(max_length=255, verbose_name='Local Final')),
                ('km_rodados', models.FloatField(default=0.0, verbose_name='KM Rodados')),
                ('status_da_viagem', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('quitada', 'Quitada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status da Viagem')),
                ('carga', models.CharField(blank=True, max_length=150, null=True, verbose_name='Carga')),
                ('mic', models.CharField(blank=True, max_length=50, null=True, verbose_name='MIC')),
                ('valor_proposto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Proposto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('media', models.FloatField(default=0.0, verbose_name='Média de Consumo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_motorista', to='app.funcionario', verbose_name='Motorista')),
                ('reboque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_reboque', to='app.veiculo', verbose_name='Reboque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('veiculo_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_veiculo', to='app.veiculo', verbose_name='Veículo Principal')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'viagens',
            },
        ),
        migrations.CreateModel(
            name='Abastecida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_abastecida', models.DateField(verbose_name='Data do Abastecimento')),
                ('valor_abastecida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Abastecimento')),
                ('litros', models.FloatField(verbose_name='Litros Abastecidos')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('motorista_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.funcionario', verbose_name='Motorista Responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.veiculo', verbose_name='Veículo')),
                ('viagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.viagem', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Abastecida',
                'verbose_name_plural': 'Abastecidas',
                'db_table': 'abastecidas',
            },
        ),
    ]
