# Generated by Django 6.0.6 on 2026-06-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecida',
            options={'verbose_name': 'Abastecimento', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AddField(
            model_name='viagem',
            name='contratante',
            field=models.CharField(default='', max_length=150, verbose_name='Contratante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abastecida',
            name='data_abastecida',
            field=models.DateField(db_index=True, verbose_name='Data do Abastecimento'),
        ),
        migrations.AlterField(
            model_name='abastecida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='abastecida',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros Abastecidos'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(db_index=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.PositiveIntegerField(verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveIntegerField(verbose_name='Ano do Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_viagem', 'Em Viagem'), ('manutencao', 'Em Manutenção'), ('vendido', 'Vendido')], db_index=True, default='disponivel', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='data_inicio',
            field=models.DateField(db_index=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='km_rodados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='KM Rodados'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='media',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Média de Consumo (km/L)'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='status_da_viagem',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('quitada', 'Quitada'), ('cancelada', 'Cancelada')], db_index=True, default='planejada', max_length=20, verbose_name='Status da Viagem'),
        ),
        migrations.AlterModelTable(
            name='abastecida',
            table='abastecimentos',
        ),
    ]
