# Generated by Django 6.0.6 on 2026-07-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_veiculo_chassi_alter_veiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFuncionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status de Funcionário',
                'verbose_name_plural': 'Status de Funcionários',
                'db_table': 'status_funcionarios',
            },
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.statusfuncionario', verbose_name='Status'),
        ),
    ]
