# Generated by Django 6.0.6 on 2026-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_viagem_nota_fiscal_alter_viagem_valor_adiantamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
