# Generated by Django 6.0.6 on 2026-08-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_caixa_nota_fiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='valor_gasto',
        ),
        migrations.AddField(
            model_name='caixa',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Entrada (+)'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='valor_saida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Saída (-)'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='tipo',
            field=models.CharField(choices=[('despesa', 'Despesa / Gasto (-)'), ('adiantamento', 'Recebimento - Adiantamento (+)'), ('quitacao', 'Recebimento - Quitação (+)'), ('receita_extra', 'Entrada Externa / Receita (+)')], max_length=20, verbose_name='Tipo de Lançamento'),
        ),
    ]
