# Generated by Django 6.0.6 on 2026-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_caixa_valor_entrada_alter_caixa_valor_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Entrada (+)'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_saida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Saída (-)'),
        ),
    ]
