# Generated by Django 6.0.6 on 2026-08-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_caixa_valor_entrada_alter_caixa_valor_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.viagem', verbose_name='Viagem Origem'),
        ),
    ]
