# Generated by Django 6.0.6 on 2026-08-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_caixa_mic_remove_caixa_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Entrada (+)'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_saida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Saída (-)'),
        ),
    ]
