# Generated by Django 6.0.6 on 2026-08-02 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_statusfuncionario_alter_funcionario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='tipo',
            field=models.CharField(choices=[('despesa', 'Despesa / Gasto'), ('adiantamento', 'Recebimento - Adiantamento'), ('quitacao', 'Recebimento - Quitação'), ('receita_extra', 'Outras Receitas')], default='despesa', max_length=20, verbose_name='Tipo de Lançamento'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.viagem', verbose_name='Viagem Origem'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='centro_de_custo',
            field=models.CharField(max_length=100, verbose_name='Centro de Custo / Veículo'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='valor_proposto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Proposto'),
        ),
    ]
