# Generated by Django 6.0.6 on 2026-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_caixa_tipo_caixa_viagem_alter_caixa_centro_de_custo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='valor_pago',
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='valor_proposto',
        ),
        migrations.AddField(
            model_name='caixa',
            name='mic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MIC'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='valor_adiantamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Adiantamento'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='valor_quitacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Quitação'),
        ),
    ]
