# Generated by Django 6.0.6 on 2026-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_caixa_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecida',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
